linters-settings:
  lll:
    line-length: 180
linters:
  enable-all: true
  disable:
    - scopelint
    - maligned
    - interfacer
    - golint
    - testpackage
    - forbidigo
    - paralleltest
    - exhaustivestruct
    - goerr113
    - wrapcheck
    - gochecknoglobals
    - varnamelen
    - funlen
    - gomnd
    - containedctx