linters-settings:
  lll:
    line-length: 180
    allow-leading-space: true
linters:
  enable-all: true
  disable:
    - testpackage
    - forbidigo
    - paralleltest
    - err113
    - wrapcheck
    - gochecknoglobals
    - varnamelen
    - funlen
    - gomnd
    - containedctx
    - ireturn
    - exhaustruct
    - nolintlint
    - maintidx
    - mnd
    - dupl
    - goimports
    - gci
    - gofmt
    - gofumpt
    - revive
    - depguard
    - tagalign
    - copyloopvar
    - intrange
    - execinquery