repos:
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
      - id: go-build-mod
      - id: go-mod-tidy
      - id: go-test-mod
      - id: go-vet-mod
      - id: go-staticcheck-mod
      - id: go-fmt
      - id: go-fumpt
      - id: go-imports
      - id: go-lint
      - id: golangci-lint-mod
        args: [-c.golang-ci.yml]

  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint