FROM alpine:3.17
COPY vkv /usr/bin/vkv

# required for vkv server
EXPOSE 8080

# preinstall vault for VKV_LOGIN_COMMAND
RUN apk add --no-cache bash vault libcap && setcap -r /usr/sbin/vault

ENTRYPOINT ["/usr/bin/vkv"]