site_name: vkv
site_description: "recursively list secrets from Vaults KV2 engine in various formats"
site_author: FalcoSuessgott

repo_name: FalcoSuessgott/vkv
repo_url: https://github.com/FalcoSuessgott/vkv

docs_dir: docs/

plugins:
  - search
  - git-authors
  - git-revision-date-localized:
      locale: en
      enable_creation_date: false

nav:
  - Docs:
    - index.md
    - quickstart.md
    - installation.md
    - authentication.md
    - configuration.md
    - export.md
    - import.md
    - server.md
    - mcp.md
    - snapshots.md
    - Advanced Examples:
      - example_diff.md
      - example_fzf.md
      - example_kubernetes.md
      - example_sops.md
      - example_direnv.md
      - example_migrate_kvv1_kvv2.md
    - CI/CD Integrations:
      - cicd_gitlab.md
      - cicd_github.md
      - cicd_azure.md
    - development.md
  - CLI Reference:
    - cmd/vkv.md
    - cmd/vkv_version.md
    - cmd/vkv_export.md
    - cmd/vkv_import.md
    - cmd/vkv_list.md
    - cmd/vkv_list_engines.md
    - cmd/vkv_list_namespaces.md
    - cmd/vkv_mcp.md
    - cmd/vkv_snapshot.md
    - cmd/vkv_snapshot_save.md
    - cmd/vkv_snapshot_restore.md
    - cmd/vkv_server.md
    - cmd/vkv_completion.md
    - cmd/vkv_completion_bash.md
    - cmd/vkv_completion_zsh.md
    - cmd/vkv_completion_fish.md

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - admonition
  - def_list
  - footnotes
  - attr_list
  - md_in_html
  - tables
  - pymdownx.tasklist:
      custom_checkbox: true
  - footnotes
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

theme:
  icon:
    edit: material/pencil
    view: material/eye
    repo: fontawesome/brands/github
  name: material

  favicon: assets/favicon.ico
  logo: assets/logo.png
  language: en
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/eye
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/eye-outline
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - content.code.copy
    - content.action.edit
    - navigation.top
    - navigation.expand
    - navigation.footer

extra:
  analytics:
    provider: google
    property: G-7LC1CWDZ0M
