site_name: vkv
site_description: "recursively list secrets from Vaults KV2 engine in various formats"
site_author: FalcoSuessgott

repo_name: FalcoSuessgott/vkv
repo_url: https://github.com/FalcoSuessgott/vkv

docs_dir: docs/

plugins:
  - search
  - git-authors
  - git-revision-date-localized:
      locale: en
      enable_creation_date: false

nav:
  - vkv: 
    - index.md
    - quickstart.md
    - installation.md
    - authentication.md
    - configuration.md
    - Export:
      - export.md
      - export_formats.md
    - import.md
    - Snapshots:
      - snapshot_save.md
      - snapshot_restore.md
    - List:
      - list_namespaces.md
      - list_engines.md
    - server.md
    - Advanced Examples: 
      - example_diff.md
      - example_fzf.md
      - example_kubernetes.md
      - example_sops.md
      - example_direnv.md
    - CI/CD Integrations:
      - cicd_gitlab.md
      - cicd_github.md
      - cicd_azure.md
    - development.md

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - admonition
  - def_list
  - footnotes
  - attr_list
  - md_in_html
  - tables
  - pymdownx.tasklist:
      custom_checkbox: true
  - footnotes
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

theme:
  icon:
    edit: material/pencil
    view: material/eye
    repo: fontawesome/brands/github
  name: material
  
  favicon: assets/favicon.ico
  logo: assets/logo.png
  language: en
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/eye
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/eye-outline
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - content.code.copy
    - content.action.edit
    - navigation.top
    - navigation.expand
    - navigation.footer

extra:
  analytics:
    provider: google
    property: G-7LC1CWDZ0M