name: vhs

on:
  push:
    branches:
      - master

jobs:
  vhs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: go get
        run: go get ./...

      - name: go install
        run: go install

      - name: install vault
        run: |
          wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update && sudo apt install vault

      - name: make vault
        run:
          make vault

      # running vhs action for each tape since using a matrix would create for each tape a single job
      - name: vhs base
        uses: charmbracelet/vhs-action@main
        with:
          path: 'assets/base.tape'
          install-fonts: false

      - name: vhs yaml
        uses: charmbracelet/vhs-action@main
        with:
          path: 'assets/yaml.tape'
          install-fonts: false

      - name: vhs json
        uses: charmbracelet/vhs-action@main
        with:
          path: 'assets/json.tape'
          install-fonts: false

      - name: vhs markdown
        uses: charmbracelet/vhs-action@main
        with:
          path: 'assets/markdown.tape'
          install-fonts: false

      - name: vhs export
        uses: charmbracelet/vhs-action@main
        with:
          path: 'assets/export.tape'
          install-fonts: false

      - name: vhs diff
        uses: charmbracelet/vhs-action@main
        with:
          path: 'assets/diff.tape'
          install-fonts: false

      - name: vhs policies
        uses: charmbracelet/vhs-action@main
        with:
          path: 'assets/policies.tape'
          install-fonts: false

      - name: vhs template
        uses: charmbracelet/vhs-action@main
        with:
          path: 'assets/template.tape'
          install-fonts: false

      - uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: Update generated VHS GIF
          branch: master
          commit_user_name: vhs-action 📼
          commit_user_email: actions@github.com
          commit_author: vhs-action 📼 <actions@github.com>
          file_pattern: 'assets/*.gif'